services:
  postgres:
    image: postgres:16
    container_name: geko-backend-postgres
    environment:
      POSTGRES_DB: geko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - geko_postgres_data:/var/lib/postgresql/data

volumes:
  geko_postgres_data:
